### PR TITLE
Desolate Gully - QoL & Balancing

### PR DESCRIPTION
**Pull request by Owehttamy**
**Changes:**
> Replaced all lapis ore with gold ore (and returned the enchanting tables)
> Enchanted all stone pickaxes to efficiency 2 to balance attacking w/ defending
> Added nametags nearby the monuments to tell players to mine the emerald in the monuments

### CODE REVIEW

**Comment by Owehttamy** [comment]
+ added golden apples to itemremove

**Comment by Owehttamy** [comment]
might change pickaxes to unenchanted iron instead of eff 2 stone but not sure yet

**Comment by BTKingly** [comment]
Are you aware of the golden efficiency pickaxes currently found on the map?

**Comment by Owehttamy** [comment]
Yes, I am. But at its current state, players are unable to actually mine any of the gold ore/blocks found on the map as both stone and gold pickaxes are too weak for them. That's why I'm considering iron, but then at the trade-off of the circumstances surrounding the gold pickaxes. It's a weird situation.

**Comment by BTKingly** [comment]
Oh yeah, I had forgotten that the XML file had custom drops (not supported on TGM) for gold. Changing to iron will have to be a must. Worst case, if the result is that the monument gets mined too quickly, we can change it to a block with a slower breaking time.

**Comment by Owehttamy** [comment]
We can also just require more blocks be broken, too. But again I'll just need to do some balancing. I'll probably bother someone later to test some stuff with me

**Comment by Owehttamy** [comment]
For now, though, I'd say accept the PR because this already is a massive improvement to the map's balancing.
People are kinda dreading the map in its current state 😅

**Pull request merged**
