### PR TITLE
Itemremove gapples Brisked KOTH

### PR DESCRIPTION
**Pull request by Owehttamy**
~~**Persisto & Perspookysto**~~
~~> Add diamond chestplates and diamond boots to itemremove (they're found in wool room chests)~~

**Brisked KOTH**
> Add golden apples to itemremove

### CODE REVIEW

**Comment by BTKingly** [comment]
I'm honestly not sure how I feel about adding wool chest gear to item remove. I feel like it's part of the map's meta; better gear is there to help you get back to your side, but taking it is also a risk; if you fail you're giving the enemy better gear.

**Comment by Owehttamy** [comment]
That's a fair argument. But, from what I've seen, the majority of CTW maps don't drop wool room gear. So, this was intended to create and maintain consistency alongside those maps.
I'm open to the idea, so I'd suggest making a poll in #suggestions to see if people would prefer the risk or not so we can decide if we should make the change or not (unless this has already been decided in a previous issue)

**Comment by BTKingly** [comment]
Most CTW maps actually  _do_ drop wool room gear. A lot of CTW maps that we have, this one included were converted from PGM/Atlas. If you take a look at the original XML file, you'd notice that wool room gear is not on itemremove. 

I discussed this change with the rest of the map dev team; we feel like we would rather try to keep consistency of the original map's intended features. That being said, if anyone wants to make a new CTW map and put these items on itemremove, we're not against it. We simply want to keep true to any map that we have converted, and uphold the features that the map author intended. 

I'm not going to accept this portion of the pull request. I'm more than happy to accept the change for Brisket KOTH - if you revert the changes for Persisto and Perspookysto.

**Comment by Owehttamy** [comment]
Alright, I'll change it to only modify Brisked KOTH tonight. :)

**Comment by Owehttamy** [comment]
Updated :)

**Pull request merged**
