### PR TITLE
Christmas paradise

### PR DESCRIPTION
**Pull request by Wesdial**
The Christmas version of "Sandy Paradise"
IMGUR Album : https://imgur.com/a/3L0s7jM
and as always, the changes made in this version should not affect the gameplay of the original one.

### CODE REVIEW

**Comment by Owehttamy** [comment]
Is there meant to be jungle leaves on the tree at spawn? (looking at third image on the imgur album)

**Comment by Wesdial** [comment]
I think?

**Comment by Owehttamy** [comment]
> I think?

Are you not sure? I was just wondering since all of the other trees seem to consist of only spruce leaves.

**Comment by Wesdial** [comment]
Yes I remember now, I wanted to make the spectators spawn tree a little different from the other trees.

**Comment by BTKingly** [comment]
Hmm, why is Circulus Turres being deleted in this PR? I assume [the last PR](https://github.com/Warzone/Maps/pull/700/files) has the updated version?

**Comment by Wesdial** [comment]
Oops, That's my bad, I'm gonna have to close this PR and open a new one, because it appears that my fork was ruined so I had to delete it and create a new one.

**Pull request closed without merging**
