### PR TITLE
Fix Terrace

### PR DESCRIPTION
**Pull request by TheRealPear**
* Fixed credit to map author in spectator spawn
* Removed the secret "room" with no floors under red wool platform
* Made the entire map's biome to be plains (before it was plains, forest, swamp, and river all at once)
* Filled in bedrock gaps under the map
* Chunks should be properly pruned now
* Updated author's name in `map.json`, however signs in the map will reflect the author's original name at the time

### CODE REVIEW

**Comment by TheRealPear** [comment]
Some of the files in the `region` folder might be empty, but MCASelector didn't seem to be deleting it. I'm not sure if it is necessary for the map to load properly.

**Comment by BTKingly** [comment]
Looks all good. Out of curiosity, why set a build height of 51? I'm not even sure players go this high

**Comment by TheRealPear** [comment]
> Looks all good. Out of curiosity, why set a build height of 51? I'm not even sure players go this high

It's mainly for consistency with Terrace 2 (which has a height limit). Both maps are big, making it easy for people to build extremely tall sky-bridges to get to the wool. If you want, I'd be happy to lower the height limit or remove it altogether. I thought it would be a good way to encourage people to get to the monument and not build bridges to simply drop down with a boat.

**Comment by BTKingly** [comment]
A build height limit of 51 put the highest bridge to be ~12 blocks above the highest point on the map. There's no point in having a build height limit that high since it so high it's basically the same thing as not having one. I would lower it by 6-10 blocks.

**Comment by TheRealPear** [comment]
Would 44 blocks work? It is about 4 blocks above the highest point.

**Comment by BTKingly** [comment]
Yeah that definitely works. 
The way that TGM does buildheight is that it looks at whatever value you set, and adds a block (so build height of 1 becomes 2, 43 becomes 44). Either 43 or 44 works, just letting you know in case you ever work on any other build heights in the future.

**Pull request merged**
