### PR TITLE
Tweak Rooted CTW itemremove

### PR DESCRIPTION
**Pull request by TheRealPear**
~~Apparently someone thought it was a good idea to itemremove tall grass, (regular) apple, seed, poppy, stone, and dirt?~~

I was mistaken in my original comment about the extra items in itemremove. I've re-added it back and also included some missing items from the kit in the list as well.

### CODE REVIEW

**Comment by TBG1000** [comment]
Intentional as per the original XML of this map

**Comment by TheRealPear** [comment]
> Intentional as per the original XML of this map

I understand keeping things unchanged as much as possible, but it quickly becomes an issue when your inventory gets full of blocks and most of their kit from dead players. What if we keep the original items, but also add the missing items that should be removed (e.g oak block and leaves, iron shovel, etc.)?

**Comment by TBG1000** [comment]
Should have worded it better but yes, the items you've added are fine, and so is adding items that come with the kits. What I meant to say is that the seemingly random items (tall grass, apples, dirt, etc) were added intentionally for consistency with the XML. They also help reduce clutter, which you mention.

The items that are NOT in the itemremove but come with the kits are, in the XML, under the `<tool-repair>` module. Sadly, that's unsupported by TGM so they were left out.

In this case, simply restore the items that you removed and add the missing items that come from the kits to the itemremove.

**Comment by BTKingly** [comment]
Itemremove on PGM also functions differently than on TGM. On PGM, an item included in itemremove will have all drops disabled; wheat seeds for example just wouldn't drop at all if broken. TGM will still drop the item upon breaks. To counter this, items that create unnecessary clutter could be given the drop tag (`"drop": true`), making items disappear upon drops as well as death

**Pull request merged**
