### PR TITLE
Senex 3 Monument Name update

### PR DESCRIPTION
**Pull request by zStorMaus**
Changed Monument names from Monument A/  B to Left/ Right

### CODE REVIEW

**Comment by BTKingly** [comment]
How are right/left determined? By the defender's point of view, or the attacker's?

**Comment by zStorMaus** [comment]
> How are right/left determined? By the defender's point of view, or the attacker's?

Defenders

**Comment by BTKingly** [comment]
For any DTW map with 2 monuments, we use the attacker's perspective. To keep maps consistent, it'd also have to be that

**Comment by BTKingly** [comment]
Wait no, miscommunication. The defender's perspective is fine. Thanks!

**Pull request merged**
