### PR TITLE
Halloween 2021 rotation

### PR DESCRIPTION
**Pull request by Owehttamy**
**Changes:**
> Removed Ternio from rotation as requested in #suggestions
> Added and converted maps to Halloween counterparts (based off of last year's rotation)

Rotation subject to change given suggestions and requests.

### CODE REVIEW

**Comment by TBG1000** [comment]
Do not combine two different issues in one PR. Removing Ternio as posted in #suggestions should be a separate PR since it has nothing to do with a halloween rotation.

Other maps to add: Snowy Wars Halloween (replacing Snowy Wars) and Bloody Trident (halloween version of Fourchette)

**Comment by Owehttamy** [comment]
Are there any popular maps (small and medium) that aren't in the rotation right now? Want to know which ones should be prioritized to be added.

**Comment by BTKingly** [comment]
Unless more maps are to be added, this will be our Halloween rot. If anyone feels like there should be changes, speak up now. These changes are to go live on October 1st.

@Owehttamy if you're wanting to add/remove any maps based on your poll, I recommend making a different pull request. This one should only be for Halloween maps

**Comment by mybeary-afk** [comment]
Hey, just wanted to open a discussion on the following maps.

**Bloody Trident**
https://github.com/Warzone/Maps/tree/master/CTW%2FBloody_Trident

This map is already on the Warzone map repository, and currently on the rotation as "Fourchette".  It would be nice if we had the spookified version on the Halloween rotation as well, or replace the current map with this one.

**Hand of Lucifer** _Blitz, Rage_ > _TDM, Rage_
https://github.com/MCResourcePile/overcast-maps/tree/master/maps/hand_of_lucifer

Having looked at the Halloween repo, noticed a lack of Blitz maps on the rotation; however, knowing that a common issue with Blitz maps are that people tend to hide to delay the game further, I'll be looking to convert this to TDM within the coming days in order to incite more aggressive play.

However, I know that there's a reason why certain maps are placed into rot, so if there's any reason why a certain map I suggested shouldn't be in the rot, please feel free to let me know.

**Comment by Owehttamy** [comment]
Taking this out of the draft because it's technically ready to go, just possible tweaks or additions now.

**Comment by BTKingly** [comment]
> Hey, just wanted to open a discussion on the following maps.
....**Hand of Lucifer** 

Unfortunately I've found that rage maps were not well received as rot maps, although they are fun to set every now and then. I'd like to have some fun spooky maps that staff can set, if time permits I'll load it to the repo.

**Pull request merged**
