### PR TITLE
Monument Modes - Change SFX for 1.8 parity

### PR DESCRIPTION
**Pull request by Owehttamy**
In older versions of the game, the beacon did not have unique sound effects. Because of this, players participating in older versions of the game don't receive audible notifications of the changes to the monuments.
This PR changes the beacon sound effect to the elder guardian curse sound effect (the one you get when it curses you with mining fatigue), which is not only available for 1.8 players but also sounds more dramatic. :)

### CODE REVIEW

**Comment by Owehttamy** [comment]
It'll be fun when this change happens because it'll surprise a lot of 1.8 users lol

**Comment by BTKingly** [comment]
You probably meant to change all maps with monument modes - just wanted to point out that Sunrise Over Paradise and Sunrise Over Lava have been missed

**Comment by Owehttamy** [comment]
They were outdated and didn't have all the bells and whistles that the other maps had, which is why I discluded them, but realistically there's no reason I shouldn't have included them.
Both updated and fixed (turns out coal blocks weren't identified as an actual monument mode, lol)

**Comment by BTKingly** [comment]
I'm slightly against having all maps using the same monument modes, and would like to see these maps remain unique (especially since the modes were the ones listed in the XML file). 

These maps play well with their current modes, I see no reason to change them.

**Comment by Owehttamy** [comment]
Fixed

**Comment by BTKingly** [comment]
Sunrise Over Paradise still includes coal blocks, a mode you added

**Comment by Owehttamy** [comment]
> Sunrise Over Paradise still includes coal blocks, a mode you added

I never added coal blocks. They've been there the whole time. (just checked its commit history)

**Comment by BTKingly** [comment]
No wait, I'm blind. Looks like the monuments were actually missing coal blocks from their materials this whole time, yet they were set to change

**Pull request merged**
