### PR TITLE
Persisto: Add iron axe to player loadout

### PR DESCRIPTION
**Pull request by residal**
Wood is placed all over this map, lacking an iron axe in your starting loadout is an inconvenience.

### CODE REVIEW

**Comment by BTKingly** [comment]
There's iron on the map, so iron axes can be crafted. Why don't we add stone axes, allowing players to break wood planks, but giving them the option to upgrade if needed?

**Comment by residal** [comment]
Any map that has wood in the starting loadout should have an axe, either a stone axe or an iron axe would be suitable. However, I think most people would prefer to start with an iron axe.

**Comment by BTKingly** [comment]
Defeats the purpose of having iron on the map if the starter kit has maxed gear though. If players want an iron axe they can craft it, trading off time for the extra speed

**Comment by residal** [comment]
> Defeats the purpose of having iron on the map if the starter kit has maxed gear though. If players want an iron axe they can craft it, trading off time for the extra speed

Understandable. Players should start with a stone axe instead of an iron axe. 

Should that mean we replace the iron pickaxe with a stone pickaxe? Or would that not be necessary?

**Comment by BTKingly** [comment]
Downgrading pickaxes would result in taking longer to mine the iron needed for upgrading. I don't think it's worth it

**Pull request merged**
