### PR TITLE
A map for infected, or something.

### PR DESCRIPTION
**Pull request by Nubbcakes**

### CODE REVIEW

**Comment by Nubbcakes** [comment]
cool

**Comment by Nubbcakes** [comment]
here

**Comment by Nubbcakes** [comment]
Hello @Benny, look at my pull request ALREADY

**Comment by BennyDoesTheStuff** [comment]
You need to upload the world itself, not a zip of the world. Additionally, the world needs to be pruned and the JSON needs to be named ``map.json``

**Pull request closed without merging**
