### PR TITLE
Add Akita by ViceWatercolour & Xounaut

### PR DESCRIPTION
**Pull request by Palmidence**
It's been sitting around a while, thought it was probably time to submit it. It's a KoTH map with four teams, and you can build (except in spawns and center.) Shooting from spawn across the map is disabled with the nifty `use-bow` filter.

### CODE REVIEW

**Comment by AtditC** [comment]
Reminds me of an Avicus lobby

**Comment by BennyDoesTheStuff** [comment]
Did you prune this map?

**Comment by Palmidence** [comment]
Came straight from your build server

**Comment by Owehttamy** [comment]
Is this ever getting implemented

**Pull request closed without merging**
