### PR TITLE
Add Vertex

### PR DESCRIPTION
**Pull request by Owehttamy**

### CODE REVIEW

**Comment by BTKingly** [comment]
Does this map have a void? If so, does the region "bottom-layer" encompass it? I'm worried that players will be unable to place blocks in the void at y=1. A solution to this would be to create a blockBreak filter denying stone for that region (So long that there's no stone that players can mine elsewhere, and then create indestructible blocks).

**Comment by Owehttamy** [comment]
Players aren't allowed to place blocks over the void under any circumstances on this map. Every situation where they have to cross between 'islands' is directed by a layer of water at y=1, as seen in the map.png file below.
map

**Comment by BTKingly** [comment]
Does the water sit at y=1?

**Comment by BTKingly** [comment]
Ahh, I see. So there could be circumstances where a player might want to cross the water but would be unable to place the blocks at y=1. That's what my concern is.

**Comment by Owehttamy** [comment]
Fixed.

**Pull request merged**
