### PR TITLE
Arctic Ruins - Increase player size

### PR DESCRIPTION
**Pull request by Owehttamy**
Map could definitely fit in small rotation, so I've modified the maximum size teams to mirror that.

### CODE REVIEW

**Comment by BTKingly** [comment]
The small rotation caps out at 14 players, so setting the team sizes to 15 each is too big

**Comment by Owehttamy** [comment]
Fixed.

**Comment by BTKingly** [comment]
The playercount for this map is now at 28, again too big for the small rotation. Fixing this would be to change both team sizes to 7

**Comment by Owehttamy** [comment]
Gotcha. Am stupid

**Pull request merged**
