### PR TITLE
Add Area 51

### PR DESCRIPTION
**Pull request by Owehttamy**

### CODE REVIEW

**Comment by BTKingly** [comment]
In the past, launchpads have had issues working properly. Would this majorly affect gameplay on this map (should they be portals instead)?

**Comment by Owehttamy** [comment]
Good point. It _could_ be a portal, but this might just have to be a map we need to scrap, as the launchpad is really its only redeemable quality 😅

**Comment by BTKingly** [comment]
Is there a way to apply velocity via command blocks? They are broken atm, but if fixed this would possibly be more reliable solution to launch pads. The map could be put on hold till then

**Comment by Owehttamy** [comment]
Currently, there is no way to modify player data with command blocks. This includes a player's velocity. A string of teleport commands or spawning an instant-fuse creeper are also alternatives, but they're both inconsistent, choppy, and wouldn't feel nearly the same. Going to have to toss this map until we have better options.

**Pull request closed without merging**
