### PR TITLE
Future non-xmas rot

### PR DESCRIPTION
**Pull request by PundaChen**
Felt like doing this since I had random motivation to do this, merge once you feel the need to get rid of xmas rot
got rid of xmas maps and shuffled maps

### CODE REVIEW

**Comment by PundaChen** [comment]
idk how to fix that codacy stuff someone pls explain

**Comment by jellz** [comment]
Double check your JSON syntax

**Comment by PundaChen** [comment]
:< time to try again

**Comment by PundaChen** [comment]
I happen to be very blind and cannot see the issue

**Comment by jellz** [comment]
Let me see if I can fix it

**Comment by jellz** [comment]
It's able to be merged now

**Comment by PundaChen** [comment]
Thank you

**Comment by BTKingly** [comment]
Whoops I honestly thought this was merged already. 
Golden Gate isn't a Christmas map... I assume you're just updating the rot at the same time?

**Comment by PundaChen** [comment]
Yes

**Pull request merged**
